### ISSUE TITLE
respect system preference changes always

### ISSUE THREAD

**Issue by hedyhli** [Xithrius/xithrius.cloud#180]
**Is your feature request related to a problem? Please describe.**
> _A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

yes I am always frustrated when my eyes are blinded by the light theme when my device automatically switches to dark mode at dusk but your site does not change. this is important because I might be reading your blog posts in the day, having put it off, continue reading at night. your visitors might be whisked away if the blinding lights annoyed them.

**Describe the solution you'd like**
> _A clear and concise description of what you want to happen._

it must follow system changes! (even after I've clicked on the toggle button to preview how to site looks like in both modes)

**Describe alternatives you've considered**
> _A clear and concise description of any alternative solutions or features you've considered._

python-discord/site#1176  see example implementation :D

**Additional context**
> _Add any other context or screenshots about the feature request here._

surrender to the pressures of modern web UX standards! /s

this should be a bug report instead. oops.

by the way I like that you also practice competitive programming
[cses](https://cses.fi/) is also a great site in addition to the ones you mentioned.

by the way 2, you can add labels to your issue templates so all feature/bug issues get the corresponding labels automatically

**Comment by Xithrius** [comment]
![homer](https://github.com/Xithrius/xithrius.cloud/assets/15021300/66b4960c-8e56-4896-9ba9-2db9744ef5aa)

**Comment by Xithrius** [comment]
@hedyhli I believe the issue has been fixed. Are you still experiencing it?

**Comment by hedyhli** [comment]
nup it's still the same

> it must follow system changes! (even after I've clicked on the toggle button to preview how to site looks like in both modes)

I mentioned last time in discord about dark/light vs 'system'
so issue is probably here

https://github.com/Xithrius/xithrius.cloud/blob/f40777df3fdfe0bb66dd632cb64309600a33f663/site/components/App/ThemeToggle.vue#L9

but in that case I can't think of any good solutions, so if you do manage to fix it it'd be amazing and impressive

**Comment by Xithrius** [comment]
I will think with brain more

**Comment by Xithrius** [comment]
ok I fixed it

**Comment by hedyhli** [comment]
good solution!!
